# Version Control & Git

::: callout-note
## Key Points

-   Version control your RAP using Git

-   Use Github to collaborate on your RAP

-   Do not push your data or sensitive parameters to Github

-   Keep an up to date version of your RAP and your data on Sharepoint.
:::

## Git

Version control is important to provide an audit trail for your work. You can see what changes have been made, when, and by who. It also means that any changes made that end up breaking your RAP can be easily reversed, and you can revert to a working version. The RAP template automatically enables git support.

Git is open source software that handles version control, and is the most widely used system. It is most commonly used through the command line, but there a are GUI options available.

Now we have the template for our RAP we should add it to a Git repository, or repo.

A thorough explanation of Git commands is beyond the scope of this book but there is a lot of separate training available. [Here](https://education.github.com/git-cheat-sheet-education.pdf) is a cheat sheet to give a quick overview of Git commands.

::: {.callout-note collapse="true"}
## Install Git and Configure Github

### Install Git

Git is a program available from within the Company Portal in your Start menu. The software is called 'Git For Windows', and will be available in the 'Apps' category. You will need to install this software before proceeding any further.

### Link Git and RStudio

Once you have installed Git, or if you already have it installed, start by telling RStudio where it can find Git. The first thing you will need to do is to identify where Git has been installed on your computer. In the Terminal tab (please note: this is *not* the same as the Console tab) in RStudio, type the following:

    where git

This should produce the location of the installation of Git on your machine.

Once you have done this, you will need to:

-   Navigate to the `Tools` menu, and select `Global Options`.
-   Click on `Git/SVN`.
-   Check *Enable version control interface for Rstudio projects*.
-   Set the path to the path given when using the `where git` command in the terminal.
-   Check *use Git bash as shell for Git projects*.

RStudio has a git pane in the top right corner. This lets you see the changes you have yet to commit, which branch you are working in, and provides a GUI interface for comitting and pushing changes.

## Github

Github is a web based platform designed to facilitate collaboration when working on projects version controlled with Git. There are a number of similar services, some with similar names (i.e. Gitlab), they share many similarities, but will have some differing features.

If you do not already have a Github account, now is the time to create one.

### Configure GitHub in RStudio

Github can be linked with RStudio to streamline the version control process.

First, you now need to tell GitHub who you are. Open Git Shell by navigating to `Tools > Shell` in the RStudio menu. In the shell, type the following command (replacing "mygithubusername" with your actual GitHub username, keeping the quotation marks):

    git config --global user.name "yourgithubusername"

Next, type the following command, including the email address you used to make your account:

    git config --global user.email "your@email.address"

You can then check the configuration was successful by typing `git config --global --list`. It should return something like the following:

    user.name=yourgithubusername
    user.email=your@email.address

You should make a commit of the current version of the project by using Git\>Commit in RStudio. Make sure to add a comment, such as "initial commit".

Now, you can run the snippet of code under the header "Adding GitHub support", which will generate a private Github repository in the DHSC organisation.

### Push your project to GitHub

Now that you're set up with Git and RStudio, it's time to push your new project to GitHub.

Open GitHub in your web browser, and create a new repository. You can do this as a personal repository, or from within any GitHub organisation to which you have access (e.g. DATAS-DHSC). Make sure you give it the exact same name as your RStudio project, but do **not** check the *Initialize this repository with a README* option. Finish this by clicking the *Create Project* option.

From your GitHub browser window, you will need to copy the two lines of code from the box labelled *Push an existing repository from the command line* They may look something like this, depnding on whether it is a personal or organisation-level repository:

    git remote add origin https://github.com/USERNAME/PROJECT.git
    git push -u origin master

Back in RStudio, make sure RStudio is using your new project as the working directory, and ensure the `Git` tab is available in the top right window. (This is the window that also contains the `Environment` and `History` tabs, among others.)

Open `Tools > Shell` again, and paste in the two lines of code you copied from GitHub. Press enter or return to finish. Your repository, and all its template files, should now be available within the online repository.
:::

## Using Git and Github in DHSC

Github is an important tool for version control and collaborative working, but it is important to keep the most up to date working version of your code - the production version - on Sharepoint. The recommended workflow is to checkout the main branch from Github into a shared folder project folder alongside other project documentation, data, etc. Analysts will clone the main branch from Github on to their local machine, and make any changes on a branch. When these changes have been QA'd, they will be merged into the main branch. The production version of the code in the shared folver will then be updated with these new changes.

You should save your repos in the DHSC organisation on Github, rather than your personal area. This will help with knowledge management, and prevent any issues if you ever leave the organisation.

It is best practice to do as much of your coding in the open as possible. However in DHSC we often use sensitive data that cannot be in the public domain, and should not be shared to servers outside of the DHSC estate. This means that is important to keep data and sensitive parameters off of Github. The most up to date versions of the data and parameters can be saved alongside the production code in a shared folder. These can then be copied into your local branch to work on the code.

Files can be prevented from being pushed into a Git rep using a file called `.gitingore`. This is a list of files that will not be pushed with your code. It can refer to specific files, or to all files with a particular extension.

The template gives you the below `.gitignore` file.

        # History files.Rhistory`.Rapp.history

        # Session Data files
        .RData

        # User-specific files
        .Ruserdata

        # Example code in package build process
        *-Ex.R

        # Output files from R CMD build
        *.tar.gz

        # Output files from R CMD check
        *.Rcheck

        # RStudio files
        .Rproj.user

        # produced vignettes
        vignettes/*.html
        vignettes/*.pdf

        # OAuth2 token, see https://github.com/hadley/httr/releases/tag/v0.3
        .httr-oauth

        # knitr and R markdown default cache directories
        *_cache/
        cache/

        # Temporary files created by R markdown
        *.utf8.md
        *.knit.md

        # R Environment Variables
        .Renviron
        .Rproj.user
        .Rdata
        .DS_Store

        # Files added by usethis
        docs
        
        

::: callout-note
## Exercise: Upload your project to Github

In this section, you'll set up a project template of your own. Using any required steps above, you should:

1.  Configure Git for Rstudio

2.  Upload your project to Github
:::
